#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: CodeFlight Consulting

# Short bio or description (displayed in the header)
description: Develop concepts before code

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/boid-clear.png

#
# Flags below are optional
#

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://codeflight.io

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
#sass:
#  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
#gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# GitHub overrides these values
# https://help.github.com/articles/using-jekyll-with-pages/
# safe: true
# lsi: false
# source: your top-level directory